services:
  ecommerce.aks.productdb:
    image: mysql:latest
    container_name: ecommerce.aks.productdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql-secret-pw
      MYSQL_DATABASE: eCommerceProducts
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
    ports:
      - 3306:3306
    volumes:
      - ecommerce.aks.productdb:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce.aks.network
    hostname: ecommerce.aks.mysqldb.products

  ecommerce.aks.userdb:
    image: postgres:latest
    container_name: ecommerce.aks.userdb
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ecommerce.aks.userdb:/var/lib/postgresql
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eCommerceUsers
    networks:
      - ecommerce.aks.network

  ecommerce.aks.product.service:
    image: ghcr.io/pandyamehul/net9-ecomm-productapi:1.0
    container_name: ecommerce.aks.product.service
    restart: unless-stopped
    environment:
      MYSQL_HOST: ecommerce.aks.productdb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_DATABASE: eCommerceProducts
    ports:
      - 8080:8080
    depends_on:
      - ecommerce.aks.productdb
    networks:
      - ecommerce.aks.network

  ecommerce.aks.user.service:
    image: ghcr.io/pandyamehul/net9-ecomm-userapi:1.0
    container_name: ecommerce.aks.user.service
    restart: unless-stopped
    environment:
      POSTGRESDB_HOST: ecommerce.aks.userdb
      POSTGRESDB_PORT: 5433
      POSTGRESDB_USER: postgres
      POSTGRESDB_PASSWORD: postgres
      POSTGRESDB_NAME: eCommerceUsers
    ports:
      - 9090:9090
    depends_on:
      - ecommerce.aks.userdb
    networks:
      - ecommerce.aks.network

volumes:
  ecommerce.aks.productdb:
  ecommerce.aks.userdb:

networks:
  ecommerce.aks.network:
    name: ecommerce.aks.network
    driver: bridge
